### ISSUE TITLE
Add the ability to divide a CIDR range into smaller ranges

### ISSUE THREAD

**Issue by bschaatsbergen** [bschaatsbergen/cidr#89]
The CIDR range division feature allow users to easily divide a given CIDR range into a specified number of smaller subnets.

**Why**: this enhancement is crucial for users dealing with IP address management, allowing them to efficiently and accurately divide CIDR ranges as needed. Improving this feature will enhance the overall usability of `cidr`.

**Example:**

Introduce a `divide` subcommand, where you specify both a CIDR range as well as an integer to divide it respectively.

```
$ cidr divide 10.0.0.0/16 9
10.0.0.0/20
10.0.16.0/20
10.0.32.0/20
10.0.48.0/20
10.0.64.0/20
10.0.80.0/20
10.0.96.0/20
10.0.112.0/20
10.0.128.0/20
```

h/t @steynovich for proposing this enhancement to cidr in a 1-on-1.

**Comment by bschaatsbergen** [comment]
What are your thoughts on this feature request @DanielRieske, @mmourick and @mvanholsteijn?

**Comment by mmourick** [comment]
Sounds like a very nice feature to add to `cidr`. I'd also like to take a crack at implementing this.

**Comment by Phaze228** [comment]
Created a PR for you.
