### ISSUE TITLE
Add the total number of IPs and the total number of available IPs

### ISSUE THREAD

**Issue by TajangSec** [bschaatsbergen/cidr#90]
When calculating 10.23.9.130/30, the output Address Count: 2
![image](https://github.com/bschaatsbergen/cidr/assets/63721558/2d193b6e-7f47-44fb-8467-457bba4747bc)
However, there are 4 IPs in this address segment, including the base address and the broadcast address.
So I want to be able to output the number of all IP addresses with the number of available IP addresses.

**Comment by bschaatsbergen** [comment]
Would it be preferable if we change "Address Count:" to "Available Host Addresses:" ? I agree that the "Adress Count:" could be confusing as it's excluding the Broadcast address as well as the Base Address @TajangSec.
